Movie Recommended System

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

Data Cleaning

In [7]:
#geners
#id
#keywords
#title
#overview
#cast
#crew
movies=movies[['id','title','keywords','genres','overview','cast','crew']]

In [8]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

id          0
title       0
keywords    0
genres      0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

Data Preprocessing

In [13]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [14]:
import ast
ast.literal_eval

In [15]:
movies['genres']=movies['genres'].apply(convert)

In [16]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [18]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
def convert2(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [20]:
movies['cast']=movies['cast'].apply(convert2)

In [21]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies.iloc[1].crew

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

In [23]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [24]:
movies['crew']=movies['crew'].apply(fetch_director)

In [25]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [27]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [28]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
movies.head()

,id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [31]:
movies['tags']= movies['overview'] + movies['genres']+movies['cast']+movies['crew']+movies['keywords']

In [32]:
movies.head()

,id,title,keywords,genres,overview,cast,crew,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [33]:
new_df = movies[['id','title','tags']]

In [34]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\jaini\AppData\Local\Temp\ipykernel_24300\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [35]:
new_df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [36]:
import nltk

In [37]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [38]:
def stem(text):
    y = []
    for i in text.split():
       y.append(ps.stem(i))
    return " ".join(y)

In [39]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\jaini\AppData\Local\Temp\ipykernel_24300\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [40]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d'

In [41]:
new_df['tags']= new_df['tags'].apply(lambda x:x.lower())

C:\Users\jaini\AppData\Local\Temp\ipykernel_24300\899821970.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:x.lower())

In [42]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [45]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
cv.get_feature_names_out

In [49]:
ps.stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d')

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

Machine Learning Model

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity=cosine_similarity(vectors)

In [52]:
list(enumerate(similarity[0]))

[(0, 1.0000000000000002),
 (1, 0.08346223261119858),
 (2, 0.08603090020146065),
 (3, 0.0734718358370645),
 (4, 0.18929940971212042),
 (5, 0.10838874619051501),
 (6, 0.04024218182927669),
 (7, 0.14673479641335554),
 (8, 0.05923488777590923),
 (9, 0.0967301666813349),
 (10, 0.10259783520851541),
 (11, 0.09464970485606021),
 (12, 0.09037128496931669),
 (13, 0.04499212706658476),
 (14, 0.12824729401064427),
 (15, 0.06282808624375433),
 (16, 0.07894736842105264),
 (17, 0.13977653617040256),
 (18, 0.09493290614465533),
 (19, 0.0830812984794528),
 (20, 0.058038100008800934),
 (21, 0.10968169942141635),
 (22, 0.0662266178532522),
 (23, 0.08740748201220976),
 (24, 0.0533380747062665),
 (25, 0.05101627678885769),
 (26, 0.15389675281277312),
 (27, 0.18693292157876878),
 (28, 0.116543309349613),
 (29, 0.065033247714309),
 (30, 0.06684847767323797),
 (31, 0.15907119074394446),
 (32, 0.08520286456846099),
 (33, 0.09733285267845754),
 (34, 0.0),
 (35, 0.09933992677987831),
 (36, 0.17316974359835272),
 (37, 0.07894736842105264),
 (38, 0.08111071056538127),
 (39, 0.08226127456606226),
 (40, 0.07694837640638656),
 (41, 0.16563698349810535),
 (42, 0.0),
 (43, 0.09086217008485092),
 (44, 0.03382550457458692),
 (45, 0.08240856434303293),
 (46, 0.1391037210186643),
 (47, 0.19672236884115843),
 (48, 0.08447772061910234),
 (49, 0.0582716546748065),
 (50, 0.11295649894498103),
 (51, 0.08048436365855338),
 (52, 0.14843120879858804),
 (53, 0.042973504259354006),
 (54, 0.031219527052723135),
 (55, 0.07038153430777869),
 (56, 0.13834289277321493),
 (57, 0.024182541670333724),
 (58, 0.06748819059987714),
 (59, 0.07254762501100116),
 (60, 0.018367958959266125),
 (61, 0.23179316248638274),
 (62, 0.0837707816583391),
 (63, 0.08175191193132876),
 (64, 0.029617443887954616),
 (65, 0.019529164171612674),
 (66, 0.02249606353329238),
 (67, 0.16452254913212452),
 (68, 0.1204950466257556),
 (69, 0.02649064714130088),
 (70, 0.076004188790721),
 (71, 0.07336739820667779),
 (72, 0.13710212427677043),
 (73, 0.0331133089266261),
 (74, 0.20246457179963143),
 (75, 0.10390486669322622),
 (76, 0.07175473098524099),
 (77, 0.014394823400711486),
 (78, 0.050669459193814),
 (79, 0.0623109738595896),
 (80, 0.050464733268936676),
 (81, 0.11020775375559676),
 (82, 0.076004188790721),
 (83, 0.17996850826633903),
 (84, 0.12361284651454937),
 (85, 0.11412706387705432),
 (86, 0.07098727864204515),
 (87, 0.11128297681493143),
 (88, 0.09037128496931669),
 (89, 0.05757929360284594),
 (90, 0.06131393394849658),
 (91, 0.16692446522239718),
 (92, 0.0623109738595896),
 (93, 0.07098727864204515),
 (94, 0.1873171623163388),
 (95, 0.1404878717372541),
 (96, 0.07694837640638656),
 (97, 0.06952346619889824),
 (98, 0.07509392614826384),
 (99, 0.02666903735313325),
 (100, 0.06765100914917384),
 (101, 0.07694837640638656),
 (102, 0.12462194771917919),
 (103, 0.07987230638308718),
 (104, 0.05564148840746572),
 (105, 0.1037571695799112),
 (106, 0.0623109738595896),
 (107, 0.061806423257274694),
 (108, 0.14509525002200235),
 (109, 0.06488856845230502),
 (110, 0.04499212706658476),
 (111, 0.15018785229652767),
 (112, 0.07694837640638656),
 (113, 0.043355498476206004),
 (114, 0.04588314677411236),
 (115, 0.043747863925980714),
 (116, 0.04836508334066745),
 (117, 0.05923488777590923),
 (118, 0.03364315551262445),
 (119, 0.043355498476206004),
 (120, 0.0),
 (121, 0.11128297681493143),
 (122, 0.116543309349613),
 (123, 0.1124803176664619),
 (124, 0.06748819059987714),
 (125, 0.07843304784240032),
 (126, 0.13334518676566626),
 (127, 0.14601068654819693),
 (128, 0.0),
 (129, 0.09269795493186431),
 (130, 0.027036903521793755),
 (131, 0.10526315789473685),
 (132, 0.04499212706658476),
 (133, 0.028239124736245257),
 (134, 0.12977713690461004),
 (135, 0.0),
 (136, 0.023414645289542353),
 (137, 0.0301237616564389),
 (138, 0.12824729401064427),
 (139, 0.12072654548783007),
 (140, 0.04499212706658476),
 (141, 0.08740748201220976),
 (142, 0.08471737420873576),
 (143, 0.08671099695241201),
 (144, 0.05006261743217589),
 (145, 0.019252140716412975),
 (146, 0.016303866268150616),
 (147, 0.05564148840746572),
 (148, 0.09733285267845754),
 (149, 0.15511334686589626),
 (150, 0.16426202236672155),
 (151, 0.2029530274475215),
 (152, 0.08346223261119858),
 (153, 0.07868894753646337),
 (154, 0.06131393394849658),
 (155, 0.02043797798283219),
 (156, 0.05990422978731538),
 (157, 0.09933992677987831),
 (158, 0.13369695534647594),
 (159, 0.06362847629757779),
 (160, 0.11712303424679457),
 (161, 0.03181423814878889),
 (162, 0.0331133089266261),
 (163, 0.050669459193814),
 (164, 0.08000711205939975),
 (165, 0.04588314677411236),
 (166, 0.12515654358043973),
 (167, 0.09037128496931669),
 (168, 0.17521916101261562),
 (169, 0.08830215713766959),
 (170, 0.10650358071057624),
 (171, 0.02271554252121273),
 (172, 0.21239769762143662),
 (173, 0.023174488732966077),
 (174, 0.07792865001991967),
 (175, 0.07098727864204515),
 (176, 0.02913582733740325),
 (177, 0.0),
 (178, 0.024455799402225926),
 (179, 0.07254762501100116),
 (180, 0.022075539284417398),
 (181, 0.04499212706658476),
 (182, 0.11707322644771176),
 (183, 0.07038153430777869),
 (184, 0.177343107178349),
 (185, 0.050669459193814),
 (186, 0.05901671065234752),
 (187, 0.15389675281277312),
 (188, 0.022075539284417398),
 (189, 0.1147078669352809),
 (190, 0.08447772061910234),
 (191, 0.04891159880445185),
 (192, 0.047324852428030105),
 (193, 0.07878168645790681),
 (194, 0.0),
 (195, 0.05923488777590923),
 (196, 0.05195243334661311),
 (197, 0.036973693332326786),
 (198, 0.057353933467640436),
 (199, 0.08671099695241201),
 (200, 0.10882143751650175),
 (201, 0.0),
 (202, 0.031219527052723135),
 (203, 0.08346223261119858),
 (204, 0.04947706959952935),
 (205, 0.07443229275647868),
 (206, 0.11092107999698035),
 (207, 0.07694837640638656),
 (208, 0.12262786789699316),
 (209, 0.06765100914917384),
 (210, 0.07509392614826384),
 (211, 0.024455799402225926),
 (212, 0.06622661785325219),
 (213, 0.05901671065234752),
 (214, 0.0),
 (215, 0.06622661785325219),
 (216, 0.06488856845230502),
 (217, 0.08520286456846099),
 (218, 0.03823595564509363),
 (219, 0.09197090092274487),
 (220, 0.1777046633277277),
 (221, 0.047324852428030105),
 (222, 0.07987230638308718),
 (223, 0.10390486669322622),
 (224, 0.060833032924035954),
 (225, 0.046829290579084706),
 (226, 0.0301237616564389),
 (227, 0.08226127456606226),
 (228, 0.11037769642208699),
 (229, 0.1074861545850028),
 (230, 0.09183979479633063),
 (231, 0.0),
 (232, 0.11128297681493143),
 (233, 0.1037571695799112),
 (234, 0.08594700851870801),
 (235, 0.076004188790721),
 (236, 0.11470786693528087),
 (237, 0.0662266178532522),
 (238, 0.11092107999698035),
 (239, 0.09125667909262308),
 (240, 0.046829290579084706),
 (241, 0.07894736842105264),
 (242, 0.08111071056538127),
 (243, 0.09269795493186431),
 (244, 0.09197090092274487),
 (245, 0.08111071056538127),
 (246, 0.07594632491572426),
 (247, 0.0),
 (248, 0.04456565178215865),
 (249, 0.13834289277321493),
 (250, 0.0),
 (251, 0.04188539082916955),
 (252, 0.020277677641345318),
 (253, 0.06282808624375433),
 (254, 0.06952346619889824),
 (255, 0.0),
 (256, 0.11164843913471803),
 (257, 0.0533380747062665),
 (258, 0.01769980813511972),
 (259, 0.06131393394849658),
 (260, 0.20395079136182276),
 (261, 0.024182541670333724),
 (262, 0.10650358071057624),
 (263, 0.09733285267845754),
 (264, 0.0),
 (265, 0.02742042485535409),
 (266, 0.0989541391990587),
 (267, 0.06488856845230502),
 (268, 0.052631578947368425),
 (269, 0.029617443887954616),
 (270, 0.08830215713766959),
 (271, 0.07098727864204515),
 (272, 0.02782074420373286),
 (273, 0.021119430154775586),
 (274, 0.08977310580745099),
 (275, 0.1433848336691011),
 (276, 0.06243905410544627),
 (277, 0.053099424405359155),
 (278, 0.11707322644771176),
 (279, 0.09269795493186431),
 (280, 0.0),
 (281, 0.065033247714309),
 (282, 0.04456565178215865),
 (283, 0.02742042485535409),
 (284, 0.018367958959266125),
 (285, 0.019529164171612674),
 (286, 0.0781166566864507),
 (287, 0.025976216673306556),
 (288, 0.02742042485535409),
 (289, 0.04588314677411236),
 (290, 0.06362847629757779),
 (291, 0.05006261743217589),
 (292, 0.08885233166386385),
 (293, 0.029617443887954616),
 (294, 0.1433848336691011),
 (295, 0.10526315789473685),
 (296, 0.038778336716474064),
 (297, 0.044151078568834795),
 (298, 0.0),
 (299, 0.05945550264670635),
 (300, 0.1711905958155815),
 (301, 0.09365858115816939),
 (302, 0.06952346619889824),
 (303, 0.02782074420373286),
 (304, 0.06578947368421054),
 (305, 0.1900748713929803),
 (306, 0.08111071056538127),
 (307, 0.10876595882948199),
 (308, 0.06765100914917384),
 (309, 0.06243905410544627),
 (310, 0.03065696697424829),
 (311, 0.15018785229652765),
 (312, 0.10012523486435178),
 (313, 0.05484084971070818),
 (314, 0.0),
 (315, 0.08346223261119858),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09933992677987831),
 (320, 0.03065696697424829),
 (321, 0.0),
 (322, 0.2105263157894737),
 (323, 0.029617443887954616),
 (324, 0.024455799402225926),
 (325, 0.09933992677987831),
 (326, 0.05647824947249051),
 (327, 0.027036903521793755),
 (328, 0.02742042485535409),
 (329, 0.07894736842105264),
 (330, 0.10012523486435178),
 (331, 0.08998425413316952),
 (332, 0.106676149412533),
 (333, 0.024455799402225926),
 (334, 0.0967301666813349),
 (335, 0.046348977465932154),
 (336, 0.06917144638660747),
 (337, 0.04543108504242546),
 (338, 0.0),
 (339, 0.04891159880445185),
 (340, 0.04947706959952935),
 (341, 0.08226127456606226),
 (342, 0.16122923187750418),
 (343, 0.019252140716412975),
 (344, 0.029617443887954616),
 (345, 0.02294157338705618),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06131393394849658),
 (349, 0.076004188790721),
 (350, 0.04891159880445185),
 (351, 0.0),
 (352, 0.02742042485535409),
 (353, 0.04120428217151646),
 (354, 0.021677749238103002),
 (355, 0.03650267163704923),
 (356, 0.09037128496931669),
 (357, 0.0),
 (358, 0.0602475233128778),
 (359, 0.031219527052723135),
 (360, 0.020942695414584774),
 (361, 0.07509392614826384),
 (362, 0.09544271444636668),
 (363, 0.09909250441117726),
 (364, 0.023414645289542353),
 (365, 0.07509392614826384),
 (366, 0.05647824947249051),
 (367, 0.0),
 (368, 0.12977713690461004),
 (369, 0.12824729401064427),
 (370, 0.050669459193814),
 (371, 0.09567297464698798),
 (372, 0.047324852428030105),
 (373, 0.17292861596651865),
 (374, 0.03797316245786213),
 (375, 0.061313933948496574),
 (376, 0.046829290579084706),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05073825686188038),
 (380, 0.05195243334661311),
 (381, 0.0837707816583391),
 (382, 0.0),
 (383, 0.043355498476206004),
 (384, 0.028676966733820218),
 (385, 0.0),
 (386, 0.021873931962990357),
 (387, 0.023662426214015053),
 (388, 0.0),
 (389, 0.08740748201220976),
 (390, 0.026315789473684213),
 (391, 0.056573571480353566),
 (392, 0.0301237616564389),
 (393, 0.0),
 (394, 0.024738534799764674),
 (395, 0.0533380747062665),
 (396, 0.043747863925980714),
 (397, 0.05195243334661311),
 (398, 0.0),
 (399, 0.023662426214015053),
 (400, 0.09037128496931669),
 (401, 0.031219527052723135),
 (402, 0.07792865001991967),
 (403, 0.0830812984794528),
 (404, 0.06131393394849658),
 (405, 0.05564148840746572),
 (406, 0.0207703246198632),
 (407, 0.021300716142115247),
 (408, 0.03244428422615251),
 (409, 0.0),
 (410, 0.0978231976089037),
 (411, 0.052631578947368425),
 (412, 0.09567297464698798),
 (413, 0.1411956236812263),
 (414, 0.029617443887954616),
 (415, 0.053418342734682205),
 (416, 0.050669459193814),
 (417, 0.03244428422615251),
 (418, 0.03539961627023944),
 (419, 0.06882472016116853),
 (420, 0.1124803176664619),
 (421, 0.023174488732966077),
 (422, 0.116543309349613),
 (423, 0.04120428217151646),
 (424, 0.03721614637823934),
 (425, 0.06390214842634574),
 (426, 0.05374307729250139),
 (427, 0.026315789473684213),
 (428, 0.055824219567359015),
 (429, 0.0),
 (430, 0.050669459193814),
 (431, 0.024182541670333724),
 (432, 0.11357771260606365),
 (433, 0.031219527052723135),
 (434, 0.0),
 (435, 0.03539961627023944),
 (436, 0.0),
 (437, 0.025649458802128853),
 (438, 0.12227899701112963),
 (439, 0.026315789473684213),
 (440, 0.024738534799764674),
 (441, 0.057353933467640436),
 (442, 0.04543108504242546),
 (443, 0.06390214842634574),
 (444, 0.0),
 (445, 0.0989541391990587),
 (446, 0.023174488732966077),
 (447, 0.06446025638903101),
 (448, 0.021300716142115247),
 (449, 0.10968169942141635),
 (450, 0.021300716142115247),
 (451, 0.025031308716087945),
 (452, 0.03065696697424829),
 (453, 0.024455799402225926),
 (454, 0.11707322644771176),
 (455, 0.060833032924035954),
 (456, 0.043355498476206004),
 (457, 0.08603090020146065),
 (458, 0.043355498476206004),
 (459, 0.03458572319330373),
 (460, 0.024182541670333724),
 (461, 0.1411956236812263),
 (462, 0.032283269414765066),
 (463, 0.03244428422615251),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14509525002200233),
 (467, 0.10559715077387793),
 (468, 0.02782074420373286),
 (469, 0.05945550264670635),
 (470, 0.04543108504242546),
 (471, 0.06390214842634574),
 (472, 0.106676149412533),
 (473, 0.09269795493186431),
 (474, 0.0),
 (475, 0.043747863925980714),
 (476, 0.13530201829834768),
 (477, 0.0),
 (478, 0.05407380704358751),
 (479, 0.08797691788472335),
 (480, 0.0978231976089037),
 (481, 0.0),
 (482, 0.021873931962990357),
 (483, 0.12487810821089254),
 (484, 0.02913582733740325),
 (485, 0.052631578947368425),
 (486, 0.07992075789278003),
 (487, 0.12725695259515557),
 (488, 0.06657426652986062),
 (489, 0.0),
 (490, 0.14159846508095775),
 (491, 0.09909250441117726),
 (492, 0.076004188790721),
 (493, 0.03065696697424829),
 (494, 0.0),
 (495, 0.19088542889273336),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06765100914917384),
 (499, 0.0),
 (500, 0.025976216673306556),
 (501, 0.08175191193132876),
 (502, 0.13369695534647594),
 (503, 0.07509392614826384),
 (504, 0.0),
 (505, 0.13530201829834768),
 (506, 0.03458572319330373),
 (507, 0.255608593705383),
 (508, 0.101338918387628),
 (509, 0.022075539284417398),
 (510, 0.0989541391990587),
 (511, 0.09197090092274487),
 (512, 0.02742042485535409),
 (513, 0.14843120879858804),
 (514, 0.04947706959952935),
 (515, 0.024738534799764674),
 (516, 0.028239124736245257),
 (517, 0.0),
 (518, 0.043747863925980714),
 (519, 0.0),
 (520, 0.0),
 (521, 0.025031308716087945),
 (522, 0.024182541670333724),
 (523, 0.04836508334066745),
 (524, 0.0),
 (525, 0.047324852428030105),
 (526, 0.028239124736245257),
 (527, 0.0331133089266261),
 (528, 0.022282825891079324),
 (529, 0.16742770563222897),
 (530, 0.05564148840746572),
 (531, 0.046348977465932154),
 (532, 0.021300716142115247),
 (533, 0.0602475233128778),
 (534, 0.0837707816583391),
 (535, 0.0978231976089037),
 (536, 0.1124803176664619),
 (537, 0.06765100914917384),
 (538, 0.0),
 (539, 0.2503866978335957),
 (540, 0.07509392614826384),
 (541, 0.10559715077387793),
 (542, 0.036973693332326786),
 (543, 0.07098727864204515),
 (544, 0.05564148840746572),
 (545, 0.024738534799764674),
 (546, 0.06362847629757779),
 (547, 0.08346223261119858),
 (548, 0.0),
 (549, 0.11959121830873498),
 (550, 0.024738534799764674),
 (551, 0.03771571432023571),
 (552, 0.0),
 (553, 0.028676966733820218),
 (554, 0.0),
 (555, 0.04499212706658475),
 (556, 0.02666903735313325),
 (557, 0.12227899701112963),
 (558, 0.0),
 (559, 0.0301237616564389),
 (560, 0.03604920469572501),
 (561, 0.03181423814878889),
 (562, 0.03065696697424829),
 (563, 0.025649458802128853),
 (564, 0.08885233166386385),
 (565, 0.043355498476206004),
 (566, 0.023918243661746996),
 (567, 0.025031308716087945),
 (568, 0.1411956236812263),
 (569, 0.047324852428030105),
 (570, 0.06765100914917384),
 (571, 0.04223886030955117),
 (572, 0.10743376064838502),
 (573, 0.0207703246198632),
 (574, 0.023414645289542353),
 (575, 0.04543108504242546),
 (576, 0.05195243334661311),
 (577, 0.1976738731537168),
 (578, 0.037463432463267755),
 (579, 0.14567913668701626),
 (580, 0.024182541670333724),
 (581, 0.14567913668701626),
 (582, 0.24511108480187255),
 (583, 0.03771571432023571),
 (584, 0.08111071056538127),
 (585, 0.024455799402225926),
 (586, 0.04499212706658476),
 (587, 0.09464970485606021),
 (588, 0.025649458802128853),
 (589, 0.1163350101494222),
 (590, 0.0301237616564389),
 (591, 0.06282808624375433),
 (592, 0.021119430154775586),
 (593, 0.0),
 (594, 0.04947706959952935),
 (595, 0.16059101370939324),
 (596, 0.09269795493186431),
 (597, 0.05923488777590923),
 (598, 0.03627381250550058),
 (599, 0.02742042485535409),
 (600, 0.06882472016116853),
 (601, 0.033463724070512735),
 (602, 0.09086217008485092),
 (603, 0.05407380704358751),
 (604, 0.0662266178532522),
 (605, 0.025031308716087945),
 (606, 0.0),
 (607, 0.05695974368679319),
 (608, 0.0),
 (609, 0.046829290579084706),
 (610, 0.058038100008800934),
 (611, 0.023174488732966077),
 (612, 0.06335829046432676),
 (613, 0.03539961627023944),
 (614, 0.04891159880445185),
 (615, 0.06131393394849658),
 (616, 0.03458572319330373),
 (617, 0.05006261743217589),
 (618, 0.08830215713766959),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06488856845230502),
 (622, 0.021119430154775586),
 (623, 0.0),
 (624, 0.1037571695799112),
 (625, 0.031219527052723135),
 (626, 0.08226127456606226),
 (627, 0.10882143751650175),
 (628, 0.0),
 (629, 0.04836508334066745),
 (630, 0.024455799402225926),
 (631, 0.050669459193814),
 (632, 0.07694837640638656),
 (633, 0.022282825891079324),
 (634, 0.07421560439929402),
 (635, 0.06622661785325219),
 (636, 0.023414645289542353),
 (637, 0.024182541670333724),
 (638, 0.03382550457458692),
 (639, 0.0),
 (640, 0.05990422978731538),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10012523486435178),
 (644, 0.05006261743217589),
 (645, 0.044151078568834795),
 (646, 0.052631578947368425),
 (647, 0.04836508334066745),
 (648, 0.0301237616564389),
 (649, 0.0),
 (650, 0.05195243334661311),
 (651, 0.0),
 (652, 0.042973504259354006),
 (653, 0.10882143751650175),
 (654, 0.10385162309931599),
 (655, 0.023918243661746996),
 (656, 0.0),
 (657, 0.03458572319330373),
 (658, 0.04836508334066745),
 (659, 0.025334729596907),
 (660, 0.09365858115816941),
 (661, 0.1675415633166782),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0602475233128778),
 (665, 0.06814662756363819),
 (666, 0.05006261743217589),
 (667, 0.0),
 (668, 0.13530201829834768),
 (669, 0.03539961627023944),
 (670, 0.01749278571353299),
 (671, 0.06814662756363819),
 (672, 0.028239124736245257),
 (673, 0.019968076595771794),
 (674, 0.07098727864204515),
 (675, 0.04499212706658476),
 (676, 0.028676966733820218),
 (677, 0.025031308716087945),
 (678, 0.116543309349613),
 (679, 0.0),
 (680, 0.07509392614826384),
 (681, 0.02742042485535409),
 (682, 0.019968076595771794),
 (683, 0.04836508334066745),
 (684, 0.0),
 (685, 0.03244428422615251),
 (686, 0.03181423814878889),
 (687, 0.10390486669322622),
 (688, 0.043355498476206004),
 (689, 0.0),
 (690, 0.025031308716087945),
 (691, 0.05923488777590923),
 (692, 0.10936965981495178),
 (693, 0.03382550457458692),
 (694, 0.021873931962990357),
 (695, 0.0662266178532522),
 (696, 0.021486752129677003),
 (697, 0.0),
 (698, 0.043355498476206004),
 (699, 0.03823595564509363),
 (700, 0.028676966733820218),
 (701, 0.057353933467640436),
 (702, 0.02249606353329238),
 (703, 0.021486752129677003),
 (704, 0.06814662756363819),
 (705, 0.024455799402225926),
 (706, 0.021677749238103002),
 (707, 0.0),
 (708, 0.024738534799764674),
 (709, 0.02060214108575823),
 (710, 0.05775642214923893),
 (711, 0.052631578947368425),
 (712, 0.0),
 (713, 0.024738534799764674),
 (714, 0.0),
 (715, 0.09933992677987831),
 (716, 0.027036903521793755),
 (717, 0.0),
 (718, 0.04499212706658476),
 (719, 0.0),
 (720, 0.026315789473684213),
 (721, 0.03244428422615251),
 (722, 0.0),
 (723, 0.024455799402225926),
 (724, 0.023662426214015053),
 (725, 0.0),
 (726, 0.0),
 (727, 0.030794751789719334),
 (728, 0.07254762501100118),
 (729, 0.04891159880445185),
 (730, 0.030254451040802585),
 (731, 0.05195243334661311),
 (732, 0.06814662756363819),
 (733, 0.061313933948496574),
 (734, 0.06684847767323797),
 (735, 0.06684847767323797),
 (736, 0.029617443887954616),
 (737, 0.07694837640638656),
 (738, 0.0),
 (739, 0.03823595564509363),

In [53]:
sorted(list(enumerate(similarity[0])),reverse = True,key=lambda x:x[1]) [1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957)]

In [54]:
def recommend(movie):
    movie_index=new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [55]:
recommend('John Carter')

Riddick
Krrish
The Other Side of Heaven
The Legend of Hercules
Get Carter